# Generated by Django 3.2.9 on 2021-11-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=100)),
                ('fruit_price', models.IntegerField(null=True)),
                ('fruit_quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
