# Generated by Django 3.2.9 on 2021-11-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Ffarrerpark.thegoodboys.com.sg%2Fproduct%2Fmango-protein-shake%2F&psig=AOvVaw0augtTTlcl66VoyDX3o2i6&ust=1637406330388000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMDCgomkpPQCFQAAAAAdAAAAABAD', max_length=500),
        ),
    ]
