# Generated by Django 3.2.9 on 2021-11-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_number',
            new_name='order_number',
        ),
    ]
